# Spring properties
spring:
  application:
     name: products-service
     

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

# HTTP Server
server:
  port: 8778   # HTTP (Tomcat) port
  
  metadataMap:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}